import type { FloorReward } from '../store/useGameStore';

export interface FloorMeta {
  nameZh: string;
  nameEn: string;
  category: 'board' | 'education' | 'fantasy';
  reward?: FloorReward;
  storyZh?: string;
  storyEn?: string;
  bgColor?: string;
}

export function getFloorMeta(floorNumber: number): FloorMeta {
  return (
    floorMeta[floorNumber] ?? {
      nameZh: '神秘楼层',
      nameEn: 'Mystery Floor',
      category: 'fantasy',
    }
  );
}

export const floorMeta: Record<number, FloorMeta> = {
  1: {
    nameZh: '五子棋', nameEn: 'Gomoku', category: 'board',
    reward: { emoji: '♟️', nameZh: '智慧棋子', nameEn: 'Wisdom Piece', descriptionZh: '五子棋高手证明', descriptionEn: 'Gomoku master proof' },
    storyZh: 'Andy来到一间古老的棋室，棋盘上黑白分明，等你来下棋！',
    storyEn: 'Andy enters an ancient chess room, the board awaits!',
    bgColor: '#1a1a3e',
  },
  2: {
    nameZh: '猜数字', nameEn: 'Guess the Number', category: 'education',
    reward: { emoji: '🔢', nameZh: '数字之星', nameEn: 'Number Star', descriptionZh: '数字猜对了！', descriptionEn: 'Number guessing star' },
    storyZh: '这间房间的门上有一个神秘数字锁，Andy需要猜出密码！',
    storyEn: 'A mysterious number lock on the door—Andy must guess the code!',
    bgColor: '#0f3460',
  },
  3: {
    nameZh: '猜颜色', nameEn: 'Guess the Color', category: 'education',
    reward: { emoji: '🎨', nameZh: '彩虹画笔', nameEn: 'Rainbow Brush', descriptionZh: '颜色都认识了！', descriptionEn: 'Knows all colors!' },
    storyZh: '房间里挂满了彩色的画，来认识每一种颜色吧！',
    storyEn: 'The room is filled with colorful paintings—learn every color!',
    bgColor: '#2a1a4a',
  },
  4: {
    nameZh: '钻石棋', nameEn: 'Diamond Chess', category: 'fantasy',
    reward: { emoji: '💎', nameZh: '闪耀钻石', nameEn: 'Shining Diamond', descriptionZh: '钻石棋大师', descriptionEn: 'Diamond chess master' },
    storyZh: '钻石闪耀的奇幻棋盘，连成菱形就能获胜！',
    storyEn: 'A sparkling diamond board—connect a diamond shape to win!',
    bgColor: '#1a2a1a',
  },
  5: {
    nameZh: '英语词汇', nameEn: 'English Vocabulary', category: 'education',
    reward: { emoji: '📚', nameZh: '英语小达人', nameEn: 'English Star', descriptionZh: '英语学得真棒！', descriptionEn: 'Great at English!' },
    storyZh: '这间房间有一本魔法词典，翻开它学习英语单词！',
    storyEn: 'A magic dictionary in this room—open it to learn English words!',
    bgColor: '#1a3a2a',
  },
  6: {
    nameZh: '拼音游戏', nameEn: 'Pinyin Game', category: 'education',
    reward: { emoji: '🔤', nameZh: '拼音精灵', nameEn: 'Pinyin Fairy', descriptionZh: '拼音都学会了！', descriptionEn: 'Pinyin mastered!' },
    storyZh: '墙上写满了汉字，拼音精灵会帮助你认字！',
    storyEn: 'Chinese characters cover the walls—the pinyin fairy will help!',
    bgColor: '#2a2a1a',
  },
  7: {
    nameZh: '斗兽棋', nameEn: 'Jungle Chess', category: 'board',
    reward: { emoji: '🦁', nameZh: '丛林之王', nameEn: 'Jungle King', descriptionZh: '斗兽棋胜利者', descriptionEn: 'Jungle chess winner' },
    storyZh: '丛林里的动物们正在下棋！老鼠竟然能打败大象？',
    storyEn: 'The jungle animals are playing chess! A rat can beat an elephant?!',
    bgColor: '#1a3a1a',
  },
  8: {
    nameZh: '成语填空', nameEn: 'Idiom Fill-in', category: 'education',
    reward: { emoji: '📖', nameZh: '成语小书童', nameEn: 'Idiom Scholar', descriptionZh: '成语学得真多！', descriptionEn: 'Knows many idioms!' },
    storyZh: '书架上的成语书缺了字，帮Andy把字填回去！',
    storyEn: 'The idiom books on the shelf are missing characters—help Andy fill them in!',
    bgColor: '#3a2a1a',
  },
  9: {
    nameZh: '简化斗地主', nameEn: 'Simple Card Game', category: 'board',
    reward: { emoji: '🃏', nameZh: '纸牌高手', nameEn: 'Card Master', descriptionZh: '出牌好厉害！', descriptionEn: 'Great card player!' },
    storyZh: '这间房间有一张神奇的牌桌，来和AI比比谁先出完牌！',
    storyEn: 'A magical card table—race the AI to play all your cards!',
    bgColor: '#2a1a1a',
  },
  10: {
    nameZh: '井字棋', nameEn: 'Tic-Tac-Toe', category: 'board',
    reward: { emoji: '⭕', nameZh: '圈叉大师', nameEn: 'XO Master', descriptionZh: '井字棋高手！', descriptionEn: 'Tic-tac-toe master!' },
    storyZh: '一个简单的棋盘，画圈还是画叉？三连就能赢！',
    storyEn: 'A simple grid—circle or cross? Three in a row wins!',
    bgColor: '#1a2a3a',
  },
  11: {
    nameZh: '四子棋', nameEn: 'Connect Four', category: 'board',
    reward: { emoji: '🔴', nameZh: '四子连珠', nameEn: 'Four Connect', descriptionZh: '四子棋赢了！', descriptionEn: 'Connect four winner!' },
    storyZh: '棋子从天而降，先连成四个就获胜！',
    storyEn: 'Pieces fall from above—connect four in a row to win!',
    bgColor: '#1a1a4a',
  },
  12: {
    nameZh: '记忆翻牌', nameEn: 'Memory Match', category: 'education',
    reward: { emoji: '🧠', nameZh: '记忆超人', nameEn: 'Memory Hero', descriptionZh: '记忆力真棒！', descriptionEn: 'Super memory!' },
    storyZh: '翻开卡片找到相同的配对，考验你的记忆力！',
    storyEn: 'Flip cards to find matching pairs—test your memory!',
    bgColor: '#2a1a3a',
  },
  13: {
    nameZh: '贪吃蛇', nameEn: 'Snake', category: 'fantasy',
    reward: { emoji: '🐍', nameZh: '贪吃蛇王', nameEn: 'Snake King', descriptionZh: '蛇越吃越长！', descriptionEn: 'The snake grows longer!' },
    storyZh: '一条小蛇在花园里找食物，越吃越长！',
    storyEn: 'A little snake searches the garden for food—it grows longer!',
    bgColor: '#0f3a1a',
  },
  14: {
    nameZh: '迷宫冒险', nameEn: 'Maze', category: 'fantasy',
    reward: { emoji: '🏰', nameZh: '迷宫勇士', nameEn: 'Maze Warrior', descriptionZh: '走出迷宫了！', descriptionEn: 'Escaped the maze!' },
    storyZh: 'Andy迷路了！帮他找到迷宫的出口！',
    storyEn: 'Andy is lost! Help him find the maze exit!',
    bgColor: '#1a2a2a',
  },
  15: {
    nameZh: '打地鼠', nameEn: 'Whack-a-Mole', category: 'fantasy',
    reward: { emoji: '🔨', nameZh: '打鼠高手', nameEn: 'Mole Whacker', descriptionZh: '地鼠全打中！', descriptionEn: 'Whacked all moles!' },
    storyZh: '地鼠从洞里探出头，快用锤子敲它！',
    storyEn: 'Moles pop out of holes—whack them with your hammer!',
    bgColor: '#2a2a0f',
  },
  16: {
    nameZh: '打砖块', nameEn: 'Breakout', category: 'fantasy',
    reward: { emoji: '🧱', nameZh: '砖块粉碎者', nameEn: 'Brick Breaker', descriptionZh: '砖块全消了！', descriptionEn: 'All bricks destroyed!' },
    storyZh: '用挡板弹球，把所有砖块都打碎！',
    storyEn: 'Bounce the ball with your paddle—destroy all bricks!',
    bgColor: '#2a0f1a',
  },
  17: {
    nameZh: '数独', nameEn: 'Sudoku', category: 'education',
    reward: { emoji: '🔢', nameZh: '数独达人', nameEn: 'Sudoku Solver', descriptionZh: '数独解开了！', descriptionEn: 'Sudoku solved!' },
    storyZh: '填入1-4的数字，每行每列都不能重复！',
    storyEn: 'Fill in 1-4 numbers—no repeats in any row or column!',
    bgColor: '#1a1a3a',
  },
  18: {
    nameZh: '数学大挑战', nameEn: 'Math Quiz', category: 'education',
    reward: { emoji: '➕', nameZh: '数学天才', nameEn: 'Math Genius', descriptionZh: '算术全对了！', descriptionEn: 'All math correct!' },
    storyZh: '算术题来了！加减乘除，你能答对几道？',
    storyEn: 'Math problems! Addition, subtraction—how many can you solve?',
    bgColor: '#0f2a3a',
  },
  19: {
    nameZh: '字母排序', nameEn: 'Word Scramble', category: 'education',
    reward: { emoji: '🔤', nameZh: '字母大师', nameEn: 'Word Master', descriptionZh: '单词全拼对！', descriptionEn: 'All words unscrambled!' },
    storyZh: '打乱的字母，帮它们排成正确的单词！',
    storyEn: 'Scrambled letters—arrange them into the correct word!',
    bgColor: '#1a3a1a',
  },
  20: {
    nameZh: '颜色匹配', nameEn: 'Color Match', category: 'education',
    reward: { emoji: '🎨', nameZh: '颜色专家', nameEn: 'Color Expert', descriptionZh: '颜色全对了！', descriptionEn: 'All colors matched!' },
    storyZh: '文字颜色和内容不一样！你选对了吗？',
    storyEn: 'The text color differs from the word—can you choose correctly?',
    bgColor: '#2a1a2a',
  },
  21: {
    nameZh: '翻牌配对', nameEn: 'Flip Card', category: 'education',
    reward: { emoji: '🃏', nameZh: '翻牌达人', nameEn: 'Card Flipper', descriptionZh: '配对全找到！', descriptionEn: 'All pairs found!' },
    storyZh: '翻牌找相同的emoji，越少次数越厉害！',
    storyEn: 'Flip cards to find matching emojis—fewer flips is better!',
    bgColor: '#1a2a1a',
  },
  22: {
    nameZh: '小小钢琴', nameEn: 'Mini Piano', category: 'fantasy',
    reward: { emoji: '🎹', nameZh: '音乐小天才', nameEn: 'Music Star', descriptionZh: '弹得真好听！', descriptionEn: 'Beautiful music!' },
    storyZh: '一架魔法钢琴，按琴键弹出动听的旋律！',
    storyEn: 'A magic piano—press the keys to play melodies!',
    bgColor: '#1a0f2a',
  },
  23: {
    nameZh: '涂鸦画板', nameEn: 'Drawing', category: 'fantasy',
    reward: { emoji: '🖌️', nameZh: '小画家', nameEn: 'Little Artist', descriptionZh: '画得真好看！', descriptionEn: 'Beautiful drawing!' },
    storyZh: '这间房间有一面魔法画布，画你想画的任何东西！',
    storyEn: 'A magic canvas in this room—draw anything you want!',
    bgColor: '#2a2a1a',
  },
  24: {
    nameZh: '反应测试', nameEn: 'Reaction Test', category: 'fantasy',
    reward: { emoji: '⚡', nameZh: '闪电反应', nameEn: 'Lightning Reflex', descriptionZh: '反应真快！', descriptionEn: 'Super fast reaction!' },
    storyZh: '灯变绿时立刻点击，看看你的反应有多快！',
    storyEn: 'Click when the light turns green—how fast are you?',
    bgColor: '#1a1a2a',
  },
  25: {
    nameZh: '滑块拼图', nameEn: 'Sliding Puzzle', category: 'fantasy',
    reward: { emoji: '🧩', nameZh: '拼图高手', nameEn: 'Puzzle Solver', descriptionZh: '拼图完成了！', descriptionEn: 'Puzzle complete!' },
    storyZh: '移动数字方块，把它们排成正确的顺序！',
    storyEn: 'Slide the number tiles into the correct order!',
    bgColor: '#2a1a0f',
  },
  26: {
    nameZh: '石头剪刀布', nameEn: 'Rock Paper Scissors', category: 'board',
    reward: { emoji: '✊', nameZh: '猜拳王', nameEn: 'RPS Champion', descriptionZh: '猜拳赢了！', descriptionEn: 'RPS winner!' },
    storyZh: '石头、剪刀、布！和AI比比谁的运气好！',
    storyEn: 'Rock, paper, scissors—test your luck against the AI!',
    bgColor: '#1a3a2a',
  },
  27: {
    nameZh: '西蒙说', nameEn: 'Simon Says', category: 'education',
    reward: { emoji: '🔔', nameZh: '记忆铃铛', nameEn: 'Bell Ringer', descriptionZh: '记忆真厉害！', descriptionEn: 'Amazing memory!' },
    storyZh: '跟着颜色闪烁的顺序点击，越来越长！',
    storyEn: 'Follow the flashing colors—the sequence gets longer!',
    bgColor: '#2a0f2a',
  },
  28: {
    nameZh: '2048', nameEn: '2048', category: 'board',
    reward: { emoji: '🏆', nameZh: '数字合并王', nameEn: 'Number Merger', descriptionZh: '合到2048了！', descriptionEn: 'Reached 2048!' },
    storyZh: '滑动数字方块，相同的数字会合并，目标2048！',
    storyEn: 'Slide number tiles—same numbers merge. Reach 2048!',
    bgColor: '#1a0f1a',
  },
  29: {
    nameZh: '扫雷', nameEn: 'Minesweeper', category: 'board',
    reward: { emoji: '💣', nameZh: '扫雷英雄', nameEn: 'Mine Sweeper', descriptionZh: '雷全排除了！', descriptionEn: 'All mines cleared!' },
    storyZh: '地面下藏着地雷，用数字线索找出安全的地方！',
    storyEn: 'Mines hide underground—use number clues to find safe spots!',
    bgColor: '#0f1a2a',
  },
  31: {
    nameZh: '瞬时记忆', nameEn: 'Flash Memory', category: 'education',
    reward: { emoji: '💫', nameZh: '记忆之星', nameEn: 'Memory Star', descriptionZh: '瞬间记住了一切！', descriptionEn: 'Remembered everything instantly!' },
    storyZh: '图案一闪而过，你能记住它们吗？',
    storyEn: 'Patterns flash and vanish—can you remember them?',
    bgColor: '#1a2a3e',
  },
  32: {
    nameZh: '数字矩阵', nameEn: 'Number Matrix', category: 'education',
    reward: { emoji: '🔢', nameZh: '矩阵之眼', nameEn: 'Matrix Eye', descriptionZh: '数字矩阵全记住了！', descriptionEn: 'Number matrix memorized!' },
    storyZh: '3x3的数字矩阵闪现后消失，你还能找到每个位置的数字吗？',
    storyEn: 'A 3x3 number matrix flashes—can you recall each position?',
    bgColor: '#0f2a4e',
  },
  33: {
    nameZh: '找不同', nameEn: 'Spot the Difference', category: 'education',
    reward: { emoji: '🔍', nameZh: '火眼金睛', nameEn: 'Eagle Eye', descriptionZh: '不同全找到了！', descriptionEn: 'All differences found!' },
    storyZh: '两幅画看起来一模一样，但藏着5处不同！',
    storyEn: 'Two pictures look identical—but 5 differences hide within!',
    bgColor: '#2a1a3e',
  },
  34: {
    nameZh: '空间旋转', nameEn: 'Spatial Rotation', category: 'education',
    reward: { emoji: '🔄', nameZh: '旋转大师', nameEn: 'Rotation Master', descriptionZh: '空间感真强！', descriptionEn: 'Great spatial sense!' },
    storyZh: '图形旋转后会变成什么样？用你的空间想象力！',
    storyEn: 'What does the shape look like after rotation? Use your spatial imagination!',
    bgColor: '#1a3a2e',
  },
  35: {
    nameZh: '路径追踪', nameEn: 'Path Tracing', category: 'education',
    reward: { emoji: '🗺️', nameZh: '追踪之眼', nameEn: 'Path Tracker', descriptionZh: '路径全记住了！', descriptionEn: 'All paths remembered!' },
    storyZh: '观察一条弯曲的路径，它消失后你能重新画出来吗？',
    storyEn: 'Watch a curving path—can you redraw it after it vanishes?',
    bgColor: '#2a2a1e',
  },
  36: {
    nameZh: '折纸展开', nameEn: 'Paper Fold', category: 'education',
    reward: { emoji: '📄', nameZh: '折纸天才', nameEn: 'Origami Genius', descriptionZh: '折纸展开全对了！', descriptionEn: 'Paper unfold mastered!' },
    storyZh: '把纸折起来打一个孔，展开后孔会在哪里？',
    storyEn: 'Fold paper and punch a hole—where will the hole be when unfolded?',
    bgColor: '#1a1a4e',
  },
  37: {
    nameZh: '盲填数独', nameEn: 'Blind Sudoku', category: 'education',
    reward: { emoji: '🧩', nameZh: '盲填大师', nameEn: 'Blind Solver', descriptionZh: '盲填数独完成了！', descriptionEn: 'Blind sudoku solved!' },
    storyZh: '先记住数独题目，然后凭记忆填入数字！',
    storyEn: 'Memorize the sudoku, then fill in numbers from memory!',
    bgColor: '#2a0f2a',
  },
  38: {
    nameZh: '记忆扑克', nameEn: 'Card Memory', category: 'education',
    reward: { emoji: '🂠', nameZh: '记忆牌王', nameEn: 'Card Memorizer', descriptionZh: '扑克顺序全记住了！', descriptionEn: 'All card orders memorized!' },
    storyZh: '快速浏览一组卡牌，然后按顺序点击它们！',
    storyEn: 'Quickly scan a set of cards, then click them in order!',
    bgColor: '#1a2a1a',
  },
  39: {
    nameZh: '文字找茬', nameEn: 'Character Spot', category: 'education',
    reward: { emoji: '👁️', nameZh: '文字侦探', nameEn: 'Text Detective', descriptionZh: '找到了隐藏的字！', descriptionEn: 'Found the hidden character!' },
    storyZh: '一堆相同的字里藏着一个不同的字，快找到它！',
    storyEn: 'One different character hides among many—find it fast!',
    bgColor: '#0f2a2a',
  },
  40: {
    nameZh: '图层叠加', nameEn: 'Layer Overlay', category: 'education',
    reward: { emoji: '🔮', nameZh: '叠加之眼', nameEn: 'Overlay Eye', descriptionZh: '图层叠加全对了！', descriptionEn: 'All overlays correct!' },
    storyZh: '两个图案叠在一起会变成什么样子？',
    storyEn: 'What do two patterns look like when overlaid?',
    bgColor: '#2a1a1a',
  },
  41: {
    nameZh: '黑白棋', nameEn: 'Reversi', category: 'board',
    reward: { emoji: '⚫', nameZh: '翻转大师', nameEn: 'Flip Master', descriptionZh: '黑白棋赢了！', descriptionEn: 'Reversi winner!' },
    storyZh: '落子翻转对手的棋子，6x6的简化黑白棋！',
    storyEn: 'Place pieces to flip your opponent—simplified 6x6 Reversi!',
    bgColor: '#1a1a2a',
  },
  42: {
    nameZh: '消消乐', nameEn: 'Match-3', category: 'fantasy',
    reward: { emoji: '💎', nameZh: '宝石猎人', nameEn: 'Gem Hunter', descriptionZh: '宝石全消了！', descriptionEn: 'All gems cleared!' },
    storyZh: '交换相邻宝石，连成三个就能消除！',
    storyEn: 'Swap adjacent gems—match three in a row to clear them!',
    bgColor: '#1a2a3a',
  },
  43: {
    nameZh: '接水管', nameEn: 'Pipe Connect', category: 'fantasy',
    reward: { emoji: '🔧', nameZh: '水管工', nameEn: 'Plumber', descriptionZh: '水管接通了！', descriptionEn: 'Pipes connected!' },
    storyZh: '旋转管道碎片，让水从入口流到出口！',
    storyEn: 'Rotate pipe pieces to let water flow from entrance to exit!',
    bgColor: '#0f1a2a',
  },
  44: {
    nameZh: '七巧板', nameEn: 'Tangram', category: 'fantasy',
    reward: { emoji: '🔷', nameZh: '七巧高手', nameEn: 'Tangram Pro', descriptionZh: '七巧板拼好了！', descriptionEn: 'Tangram completed!' },
    storyZh: '用7块几何图形拼出指定的图案！',
    storyEn: 'Use 7 geometric pieces to form the target shape!',
    bgColor: '#2a1a2a',
  },
  45: {
    nameZh: '灯光谜题', nameEn: 'Lights Out', category: 'board',
    reward: { emoji: '💡', nameZh: '灯光师', nameEn: 'Light Keeper', descriptionZh: '灯全关了！', descriptionEn: 'All lights out!' },
    storyZh: '点击一盏灯会翻转它和邻居，目标全部关灯！',
    storyEn: 'Click a light to toggle it and neighbors—turn them all off!',
    bgColor: '#1a1a1a',
  },
  46: {
    nameZh: '数字排序', nameEn: 'Number Sort', category: 'education',
    reward: { emoji: '📊', nameZh: '排序达人', nameEn: 'Sort Expert', descriptionZh: '数字排好了！', descriptionEn: 'Numbers sorted!' },
    storyZh: '把乱序的数字从小到大依次点击排列！',
    storyEn: 'Click numbers in ascending order to sort them!',
    bgColor: '#1a2a2a',
  },
  47: {
    nameZh: '华容道', nameEn: 'Klotski', category: 'board',
    reward: { emoji: '🚪', nameZh: '华容道高手', nameEn: 'Klotski Master', descriptionZh: '华容道解开了！', descriptionEn: 'Klotski solved!' },
    storyZh: '移动方块让大块从出口滑出！',
    storyEn: 'Slide blocks to let the big piece escape through the exit!',
    bgColor: '#2a0f1a',
  },
  48: {
    nameZh: '推箱子', nameEn: 'Sokoban', category: 'fantasy',
    reward: { emoji: '📦', nameZh: '仓库管理员', nameEn: 'Warehouse Keeper', descriptionZh: '箱子推到了！', descriptionEn: 'Boxes in place!' },
    storyZh: '把箱子推到标记的位置，只能推不能拉！',
    storyEn: 'Push boxes to marked spots—you can only push, not pull!',
    bgColor: '#1a1a3a',
  },
  49: {
    nameZh: '俄罗斯方块', nameEn: 'Tetris', category: 'fantasy',
    reward: { emoji: '🟦', nameZh: '方块大师', nameEn: 'Block Master', descriptionZh: '俄罗斯方块高手！', descriptionEn: 'Tetris master!' },
    storyZh: '方块从天而降，旋转摆放消除整行！',
    storyEn: 'Blocks fall from above—rotate and place to clear lines!',
    bgColor: '#0f2a1a',
  },
  50: {
    nameZh: '弹珠台', nameEn: 'Pinball', category: 'fantasy',
    reward: { emoji: '🎱', nameZh: '弹珠高手', nameEn: 'Pinball Wizard', descriptionZh: '弹珠得分真高！', descriptionEn: 'High pinball score!' },
    storyZh: '用挡板弹射弹珠，击中目标得分！',
    storyEn: 'Use flippers to launch the ball and hit targets for points!',
    bgColor: '#1a0f2a',
  },
  51: {
    nameZh: '图形推理', nameEn: 'Pattern Logic', category: 'education',
    reward: { emoji: '🧠', nameZh: '推理之王', nameEn: 'Logic King', descriptionZh: '图形规律全找到了！', descriptionEn: 'All patterns found!' },
    storyZh: '观察图形序列的规律，选出下一个图形！',
    storyEn: 'Observe the pattern sequence—choose the next shape!',
    bgColor: '#2a1a0f',
  },
  52: {
    nameZh: '速算24点', nameEn: 'Make 24', category: 'education',
    reward: { emoji: '🎯', nameZh: '速算高手', nameEn: 'Quick Calc', descriptionZh: '24点算出来了！', descriptionEn: 'Made 24!' },
    storyZh: '用4个数字和加减乘除算出24！',
    storyEn: 'Use 4 numbers and +−×÷ to make 24!',
    bgColor: '#1a2a0f',
  },
  53: {
    nameZh: '骨牌推理', nameEn: 'Domino Logic', category: 'board',
    reward: { emoji: '🁡', nameZh: '骨牌大师', nameEn: 'Domino Master', descriptionZh: '骨牌推理全对！', descriptionEn: 'All dominoes deduced!' },
    storyZh: '根据已知骨牌排列，推断出缺失的骨牌！',
    storyEn: 'Deduce the missing dominoes from the known arrangement!',
    bgColor: '#0f1a1a',
  },
  54: {
    nameZh: '词语接龙', nameEn: 'Word Chain', category: 'education',
    reward: { emoji: '🔗', nameZh: '接龙达人', nameEn: 'Chain Master', descriptionZh: '词语接龙真厉害！', descriptionEn: 'Word chain champion!' },
    storyZh: '上一个词的末字是下一个词的首字，看你能接多长！',
    storyEn: 'Each word ends where the next begins—how long can you chain?',
    bgColor: '#2a2a0f',
  },
  55: {
    nameZh: '摩斯密码', nameEn: 'Morse Code', category: 'education',
    reward: { emoji: '📡', nameZh: '密码破译者', nameEn: 'Code Breaker', descriptionZh: '密码破译了！', descriptionEn: 'Code cracked!' },
    storyZh: '用点和划组成的密码，破译隐藏的字母！',
    storyEn: 'Decode the dots and dashes to reveal hidden letters!',
    bgColor: '#0f0f2a',
  },
  56: {
    nameZh: '逻辑门', nameEn: 'Logic Gates', category: 'education',
    reward: { emoji: '⚙️', nameZh: '逻辑工程师', nameEn: 'Logic Engineer', descriptionZh: '逻辑门全对了！', descriptionEn: 'All logic gates correct!' },
    storyZh: '输入信号经过逻辑门后输出什么？AND、OR、NOT！',
    storyEn: 'What comes out after the logic gate? AND, OR, NOT!',
    bgColor: '#1a0f1a',
  },
  57: {
    nameZh: '拼字游戏', nameEn: 'Word Build', category: 'education',
    reward: { emoji: '✏️', nameZh: '拼字达人', nameEn: 'Word Builder', descriptionZh: '拼出了好多词！', descriptionEn: 'Built many words!' },
    storyZh: '用给定的字母拼出尽可能多的英语单词！',
    storyEn: 'Use the given letters to spell as many English words as possible!',
    bgColor: '#2a1a1a',
  },
  58: {
    nameZh: '算式消消乐', nameEn: 'Math Match', category: 'education',
    reward: { emoji: '🧮', nameZh: '算术达人', nameEn: 'Math Matcher', descriptionZh: '算式全配对了！', descriptionEn: 'All equations matched!' },
    storyZh: '把算式和正确的答案配对消除！',
    storyEn: 'Match equations with their correct answers to clear them!',
    bgColor: '#1a2a2a',
  },
  59: {
    nameZh: '颜色排序', nameEn: 'Color Sort', category: 'fantasy',
    reward: { emoji: '🌈', nameZh: '色彩大师', nameEn: 'Color Sorter', descriptionZh: '颜色排好了！', descriptionEn: 'Colors sorted!' },
    storyZh: '把不同颜色的水倒来倒去，让同色归一管！',
    storyEn: 'Pour colored water between tubes—same color in each tube!',
    bgColor: '#2a0f2a',
  },
  60: {
    nameZh: '连线配对', nameEn: 'Connect Pairs', category: 'education',
    reward: { emoji: '🔗', nameZh: '配对专家', nameEn: 'Pair Expert', descriptionZh: '配对全对了！', descriptionEn: 'All pairs matched!' },
    storyZh: '把左右两列相关的内容用线连起来！',
    storyEn: 'Connect related items from left and right columns!',
    bgColor: '#0f2a0f',
  },
  30: {
    nameZh: '成语消消乐', nameEn: 'Idiom Match', category: 'education',
    reward: { emoji: '🎭', nameZh: '成语达人', nameEn: 'Idiom Master', descriptionZh: '成语全都找到了！', descriptionEn: 'All idioms found!' },
    storyZh: '散落的文字碎片藏着成语秘密，找出正确的四个字拼成成语吧！',
    storyEn: 'Scattered characters hide idiom secrets—find the right four to form idioms!',
    bgColor: '#2a1a3a',
  },
};
